[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "libero"
version = "0.1.0"
description = "LIBERO: Benchmarking Knowledge Transfer for Lifelong Robot Learning"
authors = [
    {name = "Bo Liu", email = "bliu@cs.utexas.edu"},
    {name = "Yifeng Zhu", email = "yifengz@cs.utexas.edu"}
]
readme = "README.md"
requires-python = ">=3"
dependencies = [
    # "hydra-core==1.2.0",
    # "numpy==1.22.4",
    # "wandb==0.13.1",
    "easydict==1.9",
    # "transformers==4.21.1",
    # "opencv-python==4.6.0.66",
    # "robomimic==0.2.0",
    # "einops==0.4.1",
    # "thop==0.1.1-2209072238",
    "robosuite==1.4.0",
    "bddl==1.0.1",
    "future==0.18.2",
    # "matplotlib==3.5.3",
    "matplotlib",
    "cloudpickle==2.1.0",
    # "gym==0.25.2",
    "gym",
    "termcolor",
]

[project.scripts]
lifelong-main = "libero.lifelong.main:main"
lifelong-eval = "libero.lifelong.evaluate:main"
libero-config-copy = "scripts.config_copy:main"
libero-create-template = "scripts.create_template:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["libero*"]

[tool.setuptools.package-data]
"*" = ["*"]
